/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a sidebar manually
  bookSidebar: [
    {
      type: 'doc',
      id: 'index', // The introductory page
      label: 'Welcome',
    },
    {
      type: 'category',
      label: "A Beginner's Guide to AI",
      items: [
        '01-introduction-to-ai',
        '02-history-of-ai',
        '03-applications-of-ai',
        '04-future-of-ai',
      ],
    },
  ],
};

module.exports = sidebars;
